#!/usr/bin/env node

var levelup = require('levelup');
var diff = require('list-diff');

if (process.argv.length < 4) {
  console.log("USAGE: productDiffs oldDB currentDB");
  process.exit(1);
}

var joinDB = new levelup(process.argv[3]);
var oldJoinDB = new levelup(process.argv[2]);

var old = [ ];
var current = [ ];

var oldStream = oldJoinDB.createKeyStream();

oldStream.on("data", function (data) {
  old.push(data);
});

oldStream.on("close", function ( ) {
  var newStream = joinDB.createKeyStream();

  newStream.on("data", function (data) {
    current.push(data);
  });

  newStream.on("close", function ( ) {
    old = old.filter(function(e) {
      if (e.match(/1200$/)) {
        return true;
      } else {
        return false;
      }
    });
    current = current.filter(function(e) {
      if (e.match(/1200$/)) {
        return true;
      } else {
        return false;
      }
    });
    console.log(JSON.stringify(diff(old, current)));
  });
});
